use_default_settings:
  engines:
    remove:
      - ahmia
      - radio browser
      - torch

server:
  secret_key: "__SEARXNG_SECRET__"
  limiter: false
  public_instance: false

search:
  formats:
    - html
    - json
